### ISSUE TITLE
Remove Dependance on spark-csv_2.11-1.3.0.jar

### ISSUE THREAD

**Issue by mikeyoungyoung** [springml/spark-salesforce#14]
Trying to use this package with databricks and due to csv being included in spark 2.* you no longer need to have a dependency to the csv library. This is causing lots of issues using this package with databricks because I can't control the packages on the databricks side

**Comment by springml** [comment]
@mikeyoungyoung Thanks for reporting. This is handled via https://github.com/springml/spark-salesforce/commit/f499f91aeab8883930a553091b106ce42e2e6842
