### ISSUE TITLE
Could not resolve Maven dependencies ++ spark-salesforce-wave_2.10

### ISSUE THREAD

**Issue by kaul-vineet** [springml/spark-salesforce#2]
Hi - 

The Maven is not able to resolve and add artifact for spark-salesforce-wave_2.10 in the project. 

Please help and confirm if the jar is available and correct Maven parameter. 

Images of error attached. 

Thanks,
Vineet
![spark-salesforce-wave](https://cloud.githubusercontent.com/assets/6150969/14008127/85ffadbe-f1a3-11e5-9939-774e8a55fabb.jpg)
![spark-salesforce-wave 2](https://cloud.githubusercontent.com/assets/6150969/14008132/8c6a722e-f1a3-11e5-8add-283914d04bf7.jpg)

**Comment by springml** [comment]
Hi Vineet,

Could you please use the latest version from maven repository?

Below is the maven dependency to be added in pom.xml

<dependency>
    <groupId>com.springml</groupId>
    <artifactId>spark-salesforce-wave_2.10</artifactId>
    <version>1.0.6</version>
</dependency>

Thanks,
Sam.

**Comment by kaul-vineet** [comment]
Thanks. The Mavens details sorted it out.

Regards,
Vineet
