### ISSUE TITLE
ApiFault  exceptionCode='INVALID_LOGIN'  exceptionMessage='Invalid username, password, security token; or user locked out.

### ISSUE THREAD

**Issue by msathiyarajan** [springml/spark-salesforce#24]
I am getting the follwoing exception while running the above code to my SFDC
Error Message: Exception in thread "main" [LoginFault [ApiFault  exceptionCode='INVALID_LOGIN'
 exceptionMessage='Invalid username, password, security token; or user locked out.'

**Comment by samuel-pt** [comment]
@msathiyarajan - Please check whether you've provided password with security token appended to it

**Comment by msathiyarajan** [comment]
@samuel-pt Thanks Sam, Its working fine when I tried with your comments . closing this issue.
