### ISSUE TITLE
Support Retrieving Object fields

### ISSUE THREAD

**Issue by eyaltrabelsi** [springml/spark-salesforce#28]
@springml 

There is [SObject Describe call](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_sobject_describe.htm) which will allow the equivalent of dump.

I know it probably should include pr in [salesforce-wave-api](https://github.com/springml/salesforce-wave-api) in similar fashion to whats been done here [force-rest-api](https://github.com/jesperfj/force-rest-api/blob/75f718a2385d8daa42cee93c2b13d88b8dd4c5d9/src/main/java/com/force/api/ForceApi.java#L431)

I would write the code myself but i am having problems understanding the way to do http calls

**Comment by samuel-pt** [comment]
@eyaltrabelsi 
Already we are working on the [PR](https://github.com/springml/salesforce-wave-api/pull/7) which will add this feature. Once it got merged, we will have this feature

Thanks
