### ISSUE TITLE
Upsert Does not works!!!

### ISSUE THREAD

**Issue by jignesh2012** [springml/spark-salesforce#42]
I tried using the upsert flag option while updating data into salesforce. It failed saying cannot insert , but it should ideally update since it already exists.

**Comment by samuel-pt** [comment]
What version of spark connector you are using?
This issue was fixed in 1.1.3

**Comment by jignesh2012** [comment]
Hi Samuel

I am using com.springml:spark-salesforce_2.11:1.1.0 with databricks Python
3.

Read Code:
sf_soql="SELECT id,ds_status__c FROM DS_Recommendation__c where
ID='a1a1q000000ILDUAA4'"
SF_DF = spark.read \
    .format("com.springml.spark.salesforce") \
    .option("username",sfdc_username) \
    .option("password",sfdc_password) \
    .option("login",login_url) \
    .option("soql", sf_soql) \
    .option("version", "45.0") \
    .load()

Write Code:
SF_DF.write.format("com.springml.spark.salesforce")\
      .option("username",sfdc_username) \
      .option("password",sfdc_password) \
      .option("login",login_url) \
      .option("sfObject", "DS_Recommendation__c")\
      .option("upsert",True)\
      .save()

Read works and gives me 1 record. It fails to write back into the same
table as update throws below error.

java.lang.Exception: Batch &apos;7511q000002ky9mAAA&apos; failed. Number of
failed records is 1
---------------------------------------------------------------------------
Py4JJavaError Traceback (most recent call last) <command-137662> in <module>
() ----> 1 SF_DF.write.format("com.springml.spark.salesforce") .option(
"username",sfdc_username) .option("password",sfdc_password) .option("login",
login_url) .option("sfObject", "DS_Recommendation__c") .option("upsert",True
) .save() /databricks/spark/python/pyspark/sql/readwriter.py in save(self,
path, format, mode, partitionBy, **options) 732 self.format(format) 733 if
path is None: --> 734 self._jwrite.save() 735 else: 736 self._jwrite.save(
path) /databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py
in __call__(self, *args) 1255 answer = self.gateway_client.send_command(
command) 1256 return_value = get_return_value( -> 1257 answer,
self.gateway_client, self.target_id, self.name) 1258 1259 for temp_arg in
temp_args: /databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
61 def deco(*a, **kw): 62 try: ---> 63 return f(*a, **kw) 64 except py4j.
protocol.Py4JJavaError as e: 65 s = e.java_exception.toString()
/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py in
get_return_value(answer, gateway_client, target_id, name) 326 raise
Py4JJavaError( 327 "An error occurred while calling {0}{1}{2}.\n". --> 328
format(target_id, ".", name), value) 329 else: 330 raise Py4JError(
Py4JJavaError: An error occurred while calling o342.save. :
java.lang.Exception: Batch '7511q000002ky9mAAA' failed. Number of failed
records is 1 at
com.springml.salesforce.wave.impl.BulkAPIImpl.isCompleted(BulkAPIImpl.java:101)
at
com.springml.spark.salesforce.SFObjectWriter.writeData(SFObjectWriter.scala:44)
at
com.springml.spark.salesforce.DefaultSource.updateSalesforceObject(DefaultSource.scala:154)
at
com.springml.spark.salesforce.DefaultSource.createRelation(DefaultSource.scala:130)
at
org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:45)
at
org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:72)
at
org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:70)
at
org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:88)
at
org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:146)
at
org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:134)
at
org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$5.apply(SparkPlan.scala:187)
at
org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
at
org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:183)
at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:134) at
org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:114)
at
org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:114)
at
org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:690)
at
org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:690)
at
org.apache.spark.sql.execution.SQLExecution$$anonfun$withCustomExecutionEnv$1.apply(SQLExecution.scala:99)
at
org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:228)
at
org.apache.spark.sql.execution.SQLExecution$.withCustomExecutionEnv(SQLExecution.scala:85)
at
org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:158)
at
org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:690)
at
org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:290)
at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:284) at
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498) at
py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244) at
py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380) at
py4j.Gateway.invoke(Gateway.java:295) at
py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132) at
py4j.commands.CallCommand.execute(CallCommand.java:79) at
py4j.GatewayConnection.run(GatewayConnection.java:251) at
java.lang.Thread.run(Thread.java:748)

**Comment by samuel-pt** [comment]
@jignesh2012 - Please use 1.1.3 and let us know if you still facing the issue

**Comment by jignesh2012** [comment]
So it means that other versions dont work?? If there is an issue with this
package, I will prefer to use some other open source package.

**Comment by samuel-pt** [comment]
Fine

**Comment by jignesh2012** [comment]
Hi Samuel

I was able to geth the bulk working finally.. something was wrong when I
give pkchunking values..

But now i have another issue where the write fails due batch records
exceeded issue .. one where we get 10002 records and Bulk API limit is
10000.

Are you aware of this issue?
Appreciate your help!!!

Thanks
Jignesh

**Comment by mohankumarsivakumar** [comment]
Hi @jignesh2012 and @samuel-pt ,
just wanted to know the versions of dependent jars you used and working example for upsert. I am facing an issue very similar to https://github.com/springml/spark-salesforce/issues/45

**Comment by dsp404** [comment]
@samuel-pt , I am able to insert data but when I am trying to update the records using batch process, it is failing. But I am able to update records manually through work bench. Is there any issue with the option I am using as below
  SFWrite_DF.write.format("com.springml.spark.salesforce")\
      .option("username",sfdc_username) \
      .option("password",sfdc_password) \
      .option("sfObject", sfObjectName)\
      .option("login",login_url) \
      .option("bulk", True) \
      .option("upsert",True)\
      .option("version", "45.0") \
      .save()

Accessing https://tfs-3--beta.my.salesforce.com/services/async/45.0/job/7500v000008xP8PAAU/batch/7510v000006yhIHAAY/result failed. Status 400. Reason Bad Request
