### ISSUE TITLE
Glue Job fails with: Cannot create XMLStreamReader or XMLEventReader from a org.codehaus.stax2.io.Stax2ByteArraySource

### ISSUE THREAD

**Issue by it-am** [springml/spark-salesforce#62]
Unfortunately, I am not able to read from Salesforce using AWS Glue Job as soon as I add 2 following options: 
`.option("bulk", bulk)`
`.option("sfObject", sfObject)`
, where bulk is set to True (bool), sfObject is the name of the SalesForce object (string).

Everything works if I use just: `salesforce_dataframe = spark.read.format("com.springml.spark.salesforce").option("soql",soql).option("username", username).option("password", password).load()`, but in order to be able to read large object I would like to use `bulk` option. Could you please advise if you are aware of this problem and may know the root cause. Thanks!

AWS GLUE JOB LOGS:
`Traceback (most recent call last):  File "/tmp/salesforce-alex", line 33, in <module>    salesforce_dataframe = spark.read.format("com.springml.spark.salesforce").option("soql",soql).option("username", username).option("password", password).option("bulk", bulk).option("sfObject", sfObject).load()  File "/opt/amazon/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 172, in load    return self._df(self._jreader.load())  File "/opt/amazon/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__    answer, self.gateway_client, self.target_id, self.name)  File "/opt/amazon/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco    return f(*a, **kw)  File "/opt/amazon/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value    format(target_id, ".", name), value)`

`py4j.protocol.Py4JJavaError: An error occurred while calling o79.load.: java.lang.UnsupportedOperationException: Cannot create XMLStreamReader or XMLEventReader from a org.codehaus.stax2.io.Stax2ByteArraySource	at com.sun.xml.internal.stream.XMLInputFactoryImpl.jaxpSourcetoXMLInputSource(XMLInputFactoryImpl.java:302)	at com.sun.xml.internal.stream.XMLInputFactoryImpl.createXMLStreamReader(XMLInputFactoryImpl.java:143)	at com.fasterxml.jackson.dataformat.xml.XmlFactory._createParser(XmlFactory.java:595)	at com.fasterxml.jackson.dataformat.xml.XmlFactory._createParser(XmlFactory.java:29)	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:839)	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2819)	at com.springml.salesforce.wave.impl.BulkAPIImpl.addBatch(BulkAPIImpl.java:76)	at com.springml.spark.salesforce.BulkRelation.records$lzycompute(BulkRelation.scala:50)	at com.springml.spark.salesforce.BulkRelation.records(BulkRelation.scala:45)	at com.springml.spark.salesforce.BulkRelation.schema(BulkRelation.scala:40)	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:403)	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223)	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:167)	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)	at java.lang.reflect.Method.invoke(Method.java:498)	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)	at py4j.Gateway.invoke(Gateway.java:282)	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)	at py4j.commands.CallCommand.execute(CallCommand.java:79)	at py4j.GatewayConnection.run(GatewayConnection.java:238)	at java.lang.Thread.run(Thread.java:748)`

**Comment by it-am** [comment]
FYI: 
For testing, I created a dev salesforce account which is pre-populated with some data already, and as a `soql ` I am using the following: `soql = "select name, accountnumber, industry, type, billingaddress, sic from account"`

**Comment by dkennedy-eng** [comment]
hey @it-am, were you able to solve this? Having exactly the same issue

**Comment by dkennedy-eng** [comment]
From your other question it doesn't look like you changed anything, did you update the dependent libraries or something? I think we're working off the same AWS Glue article

**Comment by dkennedy-eng** [comment]
Anyone who stumbles across this, the below solution fixed it for me 

https://stackoverflow.com/questions/67063848/springml-salesforce-cannot-create-xmlstreamreader-from-org-codehaus-stax2-io-st
